- job_name: 'amq-brokers'
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    action: keep
    regex: ((.+-)*broker-amq-tcp)
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    action: keep
    regex: prometheus
  - source_labels: [__meta_kubernetes_namespace]
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_service_name]
    regex: (.+)*-broker-amq-tcp
    target_label: service
    replacement: $1
    action: replace
